function tableData = standardizeOutputTable(tableData, context)
%STANDARDIZEOUTPUTTABLE Apply readable output names and explicit units.
%
% Inputs
%   tableData Result table generated by an analysis module.
%   context   One of "global", "plaques", "layers", or "spheres".
%
% Output
%   tableData Table with standardized metadata names and unit suffixes.

    if isempty(tableData)
        return;
    end

    context = string(context);
    exactMap = getExactNameMap();
    oldNames = string(tableData.Properties.VariableNames);
    newNames = oldNames;

    for i = 1:numel(oldNames)
        name = oldNames(i);
        validField = matlab.lang.makeValidName(name);
        if isfield(exactMap, validField)
            if name == "MicrogliaDensityTotal" && context == "layers"
                newNames(i) = "MicrogliaDensityTotal_cells_mm3";
            else
                newNames(i) = string(exactMap.(validField));
            end
        else
            newNames(i) = standardizeDynamicName(name, context);
        end
    end

    newNames = string(matlab.lang.makeUniqueStrings(cellstr(newNames)));
    tableData.Properties.VariableNames = cellstr(newNames);
end

function map = getExactNameMap()
%GETEXACTNAMEMAP Return exact legacy-to-standard output mappings.
    map.File = "FileName";
    map.Mouse = "MouseID";
    map.Section = "SectionID";
    map.Image = "ImageID";
    map.CortexArea = "CorticalRegion";
    map.LayerInformationAvailable = "LayerInformationAvailable";
    map.VolumeTotal = "TotalTissueVolume_um3";
    map.AnalyzedVolume = "AnalyzedVolume_um3";
    map.VolumeValid = "AnalyzedVolume_um3";
    map.MicrogliaNumber = "MicrogliaCount_AnalyzedVolume";
    map.MicrogliaDensity = "MicrogliaDensity_AnalyzedVolume_cells_mm3";
    map.ValidMicroglia = "ValidVoronoiCellCount";
    map.MeanNeighs = "MeanVoronoiNeighborCount";
    map.StdNeighs = "StdVoronoiNeighborCount";
    map.MeanSurface = "MeanVoronoiSurfaceArea_um2";
    map.StdSurface = "StdVoronoiSurfaceArea_um2";
    map.MeanVolume = "MeanVoronoiVolume_um3";
    map.StdVolume = "StdVoronoiVolume_um3";
    map.MeanDistNeighs = "MeanVoronoiNeighborDistance_um";
    map.StdDistNeighs = "StdVoronoiNeighborDistance_um";
    map.PlaqueNumberTotal = "TotalPlaqueCount";
    map.PlaqueNumberValid = "PlaqueCount_AnalyzedVolume";
    map.PlaqueDensityTotal = "TotalPlaqueDensity_plaques_mm3";
    map.PlaqueDensityValid = "PlaqueDensity_AnalyzedVolume_plaques_mm3";
    map.PlaqueVolumeOccupied_Total = "TotalPlaqueVolume_um3";
    map.PlaqueVolumeOccupied_Valid = "PlaqueVolume_AnalyzedVolume_um3";
    map.PlaquePercOccupied_Total = "TotalPlaqueOccupiedFraction";
    map.PlaquePercOccupied_Valid = "PlaqueOccupiedFraction_AnalyzedVolume";
    map.IDPlaque = "PlaqueID_Image";
    map.IDSphere = "SphereID";
    map.ImageSphereID = "ImageSphereID";
    map.TypeSphere = "SphereType";
    map.IDImage = "ImageID";

    map.PlaqueVolume = "PlaqueVolume_um3";
    map.PlaqueVolumeValid = "PlaqueVolume_AnalyzedVolume_um3";
    map.NAssociatedMicroglia = "AssociatedMicrogliaCount";
    map.NInsideMicroglia = "InsidePlaqueMicrogliaCount";
    map.NAroundMicroglia = "PeriplaqueMicrogliaCount";
    map.MicrogliaDensityTotal = "AssociatedMicrogliaDensity_cells_mm3";
    map.MicrogliaDensityInside = "InsidePlaqueMicrogliaDensity_cells_mm3";
    map.MicrogliaDensityAround = "PeriplaqueMicrogliaDensity_cells_mm3";
    map.MicrogliaDist_Mean = "MeanPairwiseMicrogliaDistance_um";
    map.MicrogliaDist_Std = "StdPairwiseMicrogliaDistance_um";
    map.MicrogliaDistToNearest_Mean = "MeanNearestMicrogliaDistance_um";
    map.MicrogliaDistToNearest_Std = "StdNearestMicrogliaDistance_um";
    map.Centroid_X = "CentroidX_px";
    map.Centroid_Y = "CentroidY_px";
    map.Centroid_Z = "CentroidZ_px";
    map.CentroidX = "CentroidX_px";
    map.CentroidY = "CentroidY_px";
    map.CentroidZ = "CentroidZ_px";
    map.distToBorder = "DistanceToCorticalSurface_um";
    map.DistToBorder = "DistanceToCorticalSurface_um";
    map.DistNearestPlaque = "NearestPlaqueDistance_um";
    map.VolSphere = "SphereVolume_um3";
    map.VolOverlap = "SphereOverlapVolume_um3";
    map.nMicroglia = "MicrogliaCount";
    map.N_Plaques = "PlaqueCount";
    map.Plaque_Density = "PlaqueDensity_plaques_mm3";
    map.N_Valid_Plaques = "PlaqueCount_AnalyzedVolume";
    map.Plaque_Density_Valid = "PlaqueDensity_AnalyzedVolume_plaques_mm3";
    map.Volume_Total = "TotalTissueVolume_um3";
    map.Valid_Volume = "AnalyzedVolume_um3";
    map.N_Valid_Microglia = "MicrogliaCount_AnalyzedVolume";
end

function newName = standardizeDynamicName(name, context)
%STANDARDIZEDYNAMICNAME Add units to repeated layer, sphere, and Voronoi fields.
    newName = name;

    replacements = {
        'MicrogliaDensitymm3$', 'MicrogliaDensity_cells_mm3';
        'MicrogliaDensity$', 'MicrogliaDensity_cells_mm3';
        'PlaquesDensitymm3$', 'PlaqueDensity_plaques_mm3';
        'PlaquesDensity$', 'PlaqueDensity_plaques_mm3';
        'MeanPlaquesVolume$', 'MeanPlaqueVolume_um3';
        'StdPlaquesVolume$', 'StdPlaqueVolume_um3';
        'Volume$', 'Volume_um3';
        'SurfaceArea', 'SurfaceArea_um2';
        'MeanSurface', 'MeanSurfaceArea_um2';
        'StdSurface', 'StdSurfaceArea_um2';
        'MeanVolume', 'MeanVolume_um3';
        'StdVolume', 'StdVolume_um3';
        'DistNeighs', 'NeighborDistance_um';
        'DistanceNeighbours', 'NeighborDistance_um';
        'MicrogliaDistToNearest_Mean', 'MeanNearestMicrogliaDistance_um';
        'MicrogliaDistToNearest_Std', 'StdNearestMicrogliaDistance_um';
        'MicrogliaDist_Mean', 'MeanPairwiseMicrogliaDistance_um';
        'MicrogliaDist_Std', 'StdPairwiseMicrogliaDistance_um'};

    for i = 1:size(replacements, 1)
        newName = string(regexprep(char(newName), replacements{i, 1}, replacements{i, 2}));
    end

    if context == "spheres"
        newName = replace(newName, "MicrogliaDensity", "MicrogliaDensity_cells_mm3");
        newName = replace(newName, "Vol_Plaque", "PlaqueVolume_um3");
        newName = replace(newName, "VolPlaque", "PlaqueVolume_um3");
    end
end
